<%@ Page Language="VB" AutoEventWireup="false" CodeFile="frmMultiSiteDocSetup.aspx.vb"
Inherits="frmMultiSiteDocSetup" %>
<%@ Register Assembly="System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
Namespace="System.Web.UI" TagPrefix="asp" %>
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head runat="server">
        <title></title>
        <link href="../CSS/Styles.css" rel="stylesheet" type="text/css" />
        <script language="javascript" type="text/javascript" src="../Include/Validation.js">
        </script>
        <script language="javascript" type="text/javascript">
            function checkIsEmpty(){
                var msg = "";
                if (document.getElementById('hdnSites').value == 0) {
                    msg = msg + "Sites should be select\n";
                }
                if (msg != "") {
                    alert("Mandatory field information required \n\n" + msg);
                    return false;
                }
                else {
                    return accessConfirm();
                }
            }
            
            function accessConfirm(){
                var r = confirm("Are you sure you want to save the details?");
                if (r == true) {
                    return true;
                }
                else {
                    return false;
                }
            }
            
            function myPostBack(){
                var o = window.event.srcElement;
                alert(o.value)
                if (o.tagName == "INPUT" && o.type == "checkbox") {
                    __doPostBack("", "");
                }
            }
            
            function TreeNodeCheckChanged(event, control){ // Valid for IE and Firefox/Safari/Chrome.    
                var obj = window.event ? window.event.srcElement : event.target;
                var source = window.event ? window.event.srcElement.id : event.target.id;
                source = source.replace(control.id + "t", control.id + "n");
                source = source.replace("CheckBox", "");
                var checkbox = document.getElementById(source);
                if (checkbox != null && obj.tagName == "INPUT" && obj.type == "checkbox") {
                    __doPostBack(checkbox.id, "");
                }
            }
            
            function viewSite(){
                window.open('frmSiteHelp.aspx', '', 'width=600,height=600,menubar=no,status=no,location=no,toolbar=no,scrollbars=yes,resizable=yes');
                
            }
        </script>
    </head>
    <body>
        <form id="form1" runat="server">
            <div style="width: 100%">
                <asp:ScriptManager ID="ScriptManager1" runat="server">
                </asp:ScriptManager>
                <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                    <ContentTemplate>
                        <table border="0" cellpadding="1" cellspacing="1" width="100%">
                            <tr class="pageTitle">
                                <td colspan="3">
                                    Multiple Document CheckList
                                </td>
                            </tr>
                            <tr style="height: 5">
                                <td colspan="3">
                                </td>
                            </tr>
                            <tr>
                                <td class="lblTitleM">
                                    Site
                                </td>
                                <td style="width: 1px">
                                    :
                                </td>
                                <td>
                                    <asp:DropDownList ID="ddlWF" runat="server" CssClass="selectFieldStyle" AutoPostBack="true">
                                    </asp:DropDownList>
                                    <b>
                                        <asp:Label ID="lblSite" runat="server" CssClass="lblText">
                                        </asp:Label>
                                    </b>
                                    <a id="A1" runat="server" href="#" onclick="viewSite();" class="ASmall">Select Sites</a>
                                </td>
                            </tr>
                            <tr>
                                <td class="lblTitleM">
                                    Documents
                                </td>
                                <td valign="top">
                                    :
                                </td>
                                <td>
                                    <asp:TreeView ID="TreeView1" runat="server" ShowCheckBoxes="All" AutoGenerateDataBindings="false" OnTreeNodeCheckChanged="TreeView1_TreeNodeCheckChanged" NodeIndent="10" ExpandDepth="3" MaxDataBindDepth="4" ShowLines="True" Target="None">
                                        <ParentNodeStyle Font-Bold="True" ForeColor="Blue" /><RootNodeStyle Font-Bold="True" ForeColor="Blue" /><SelectedNodeStyle BackColor="White" BorderColor="#888888" BorderStyle="None" BorderWidth="1px" Font-Underline="False" HorizontalPadding="1px" VerticalPadding="0px" /><NodeStyle CssClass="instructionalMessage" HorizontalPadding="1px" NodeSpacing="0px" VerticalPadding="0px" />
                                    </asp:TreeView>
                                </td>
                            </tr>
                            <tr style="height: 5">
                                <td colspan="3">
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                </td>
                                <td>
                                    <input id="btnCancel" type="button" value="Back" runat="server" class="buttonStyle" /><asp:Button ID="btnDelete" runat="server" Text="Delete" Visible="False" CssClass="buttonStyle" /><asp:Button ID="btnSave" runat="server" Text="Save" CssClass="buttonStyle" />
                                </td>
                            </tr>
                            <tr style="height: 10px">
                            </tr>
                            <tr>
                                <td class="ASmall">
                                    Legend:
                                </td>
                            </tr>
                            <tr class="lblText">
                                <td>
                                    Documents without Process Flow
                                </td>
                                <td>
                                    :
                                </td>
                                <td>
                                    <font style='color: OrangeRed'>
                                        <b>Orange Red</b>
                                    </font>
                                </td>
                            </tr>
                            <tr class="lblText">
                                <td>
                                    Documents without Approval Req.
                                </td>
                                <td>
                                    :
                                </td>
                                <td>
                                    <font style='color: DarkGreen'>
                                        <b>Dark Green</b>
                                    </font>
                                </td>
                            </tr>
                            <tr style="height: 10px">
                            </tr>
                        </table>
                        <asp:GridView runat="server" ID="grdDoc" AutoGenerateColumns="False" DataKeyNames="SW_Id" EmptyDataText="No Records">
                            <HeaderStyle CssClass="GridHeader" /><RowStyle CssClass="GridOddRows" /><AlternatingRowStyle CssClass="GridEvenRows" />
                            <Columns>
                                <asp:TemplateField HeaderText=" Total ">
                                    <ItemTemplate>
                                        <%# container.DataItemIndex + 1 %>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Document">
                                    <ItemTemplate>
                                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("DocName") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:BoundField DataField="Percentage" HeaderText="%" />
                                <asp:TemplateField HeaderText="%">
                                    <ItemTemplate>
                                        <input type="text" id="textperc" runat="server" maxlength="5" class="textFieldStyle" onkeypress="javascript:return allowKeyAcceptsSingleDot('0123456789.');" value='<%# DataBinder.Eval(Container.DataItem, "Percentage") %>' />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <asp:CheckBox ID="chkwf" AutoPostBack="true" runat="server" Checked="true" OnCheckedChanged="getwf" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <asp:DropDownList Visible="false" ID="ddlWF" runat="server" CssClass="selectFieldStyle">
                                        </asp:DropDownList>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:BoundField DataField="Appr_Required" HeaderText="Appr_Required" /><asp:BoundField DataField="WF_Id" HeaderText="WF_Id" /><asp:BoundField DataField="DOCId" HeaderText="DOCID" />
                            </Columns>
                        </asp:GridView>
                        <br/>
                        <asp:Button ID="btnEdit" runat="server" Text="Update" CssClass="buttonStyle" Visible="False" />
                    </ContentTemplate>
                </asp:UpdatePanel>&nbsp;&nbsp;<input type="hidden" id="hdnid" runat="server" /><input type="hidden" id="hdnSW_Id" runat="server" /><input type="hidden" id="hdnTotal" runat="server" /><input type="hidden" id="hdnSites" runat="server" /><input type="hidden" id="hdnpo" runat="server" />
            </div>
        </form>
    </body>
</html>