<%@ Page Language="VB" AutoEventWireup="false" CodeFile="frmSiteDocSetup.aspx.vb" EnableEventValidation="false"
    Inherits="frmSiteDocSetup" %>

<%@ Register Assembly="System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
    Namespace="System.Web.UI" TagPrefix="asp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Document Checklist</title>
    <link href="../CSS/Styles.css" rel="stylesheet" type="text/css" />

    <script language="javascript" type="text/javascript" src="../Include/Validation.js">
    </script>

    <script language="javascript" type="text/javascript">
        function checkIsEmpty() {
            var msg = "";
            var e = document.getElementById("ddlWF");
            var strUser = e.options[e.selectedIndex].value;
            if (strUser == 0) {
                msg = msg + "Site Id should be select\n";
            }
            if (msg != "") {
                alert("Mandatory field information required \n\n" + msg);
                return false;
            }
            else {
                return accessConfirm();
            }
        }

        function accessConfirm() {
            var r = confirm("Are you sure you want to save the details?");
            if (r == true) {
                return true;
            }
            else {
                return false;
            }
        }

        function Showmain() {
            alert('There is no scope for selected Site. please add Scope');
            window.location = 'frmPOSiteList.aspx';

        }

        function TreeNodeCheckChanged(event, control) { // Valid for IE and Firefox/Safari/Chrome.    
            var obj = window.event ? window.event.srcElement : event.target;
            var source = window.event ? window.event.srcElement.id : event.target.id;
            source = source.replace(control.id + "t", control.id + "n");
            source = source.replace("CheckBox", "");
            var checkbox = document.getElementById(source);
            if (checkbox != null && obj.tagName == "INPUT" && obj.type == "checkbox") {
                __doPostBack(checkbox.id, "");
            }
        }
    </script>
    <style type="text/css">
        .headerpanel {
            background-color: gray;
            padding: 4px;
            color: black;
            font-family: Trebuchet MS;
            font-size: 20px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <div style="width: 99%; height: 450px;">
            <div class="headerpanel">
                Document CheckList
            </div>
            <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                <ContentTemplate>

                    <div style="margin-top: 5px;">
                        <table border="0" cellpadding="1" cellspacing="1" width="100%">
                            <tr>
                                <td class="lblTitle">Site <font style="color: Red; font-size: 16px"><sup>* </sup></font>
                                </td>
                                <td style="width: 1%">:
                                </td>
                                <td>
                                    <asp:DropDownList ID="ddlWF" runat="server" CssClass="selectFieldStyle" AutoPostBack="true">
                                    </asp:DropDownList>
                                    <asp:Label ID="lblSite" runat="server" CssClass="lblText">
                                    </asp:Label>
                                </td>
                            </tr>
                            <tr style="display:none;">
                                <td class="lblTitle">Integration Date
                                </td>
                                <td>:
                                </td>
                                <td id="lblIntDate" runat="server" class="lblText"></td>
                            </tr>
                            <tr>
                                <td class="lblTitle" valign="top">Documents <font style="color: Red; font-size: 16px"><sup>* </sup></font>
                                </td>
                                <td valign="top">:
                                </td>
                                <td>
                                    <asp:TreeView ID="TreeView1" runat="server" ShowCheckBoxes="All" AutoGenerateDataBindings="false"
                                        NodeIndent="10" ExpandDepth="3" MaxDataBindDepth="4" ShowLines="True" Target="None">
                                        <ParentNodeStyle Font-Bold="True" ForeColor="Blue" />
                                        <RootNodeStyle Font-Bold="True" ForeColor="Blue" />
                                        <SelectedNodeStyle BackColor="White" BorderColor="#888888" BorderStyle="None" BorderWidth="1px"
                                            Font-Underline="False" HorizontalPadding="1px" VerticalPadding="0px" />
                                        <NodeStyle CssClass="instructionalMessage" HorizontalPadding="1px" NodeSpacing="0px"
                                            VerticalPadding="0px" />
                                    </asp:TreeView>
                                </td>
                            </tr>
                            <tr style="height: 5">
                                <td colspan="3"></td>
                            </tr>
                            <tr>
                                <td colspan="2"></td>
                                <td>
                                    <input id="btnCancel" type="button" value="Back" runat="server" class="buttonStyle" />
                                    <asp:Button ID="btnDelete" runat="server" Text="Delete" Visible="False" CssClass="buttonStyle" />
                                    <asp:Button ID="btnSave" runat="server" Text="Save" CssClass="buttonStyle" OnClientClick="this.style.display = 'none'; loadingdiv.style.display = '';" />
                                </td>
                            </tr>
                            <tr style="height: 10px">
                            </tr>
                            <tr>
                                <td class="ASmall">Legend:
                                </td>
                            </tr>
							 <tr>
                                <td class="lblText">Online Form
                                </td>
                                <td>:
                                </td>
                                <td>
                                    <font style="color: blue"><b>Blue</b> </font>
                                </td>
                            </tr>
                            <tr>
                                <td class="lblText">Documents without Process Flow
                                </td>
                                <td>:
                                </td>
                                <td>
                                    <font style="color: orangered"><b>Orange Red</b> </font>
                                </td>
                            </tr>
                            <tr>
                                <td class="lblText">Documents without Approval Req.
                                </td>
                                <td>:
                                </td>
                                <td>
                                    <font style="color: darkgreen"><b>Dark Green</b> </font>
                                </td>
                            </tr>
                            <tr style="height: 10px">
                                <td colspan="3"></td>
                            </tr>
                        </table>
                    </div>
                    <div style="margin-top: 10px;">
                        <asp:GridView runat="server" ID="grdDoc" AutoGenerateColumns="False" DataKeyNames="SW_Id"
                            EmptyDataText="No Records">
                            <HeaderStyle CssClass="GridHeader" />
                            <RowStyle CssClass="GridOddRows" />
                            <AlternatingRowStyle CssClass="GridEvenRows" />
                            <Columns>
                                <asp:TemplateField HeaderText=" Total ">
                                    <ItemTemplate>
                                        <%# container.DataItemIndex + 1 %>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Document">
                                    <ItemTemplate>
                                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("DocName") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:BoundField DataField="Percentage" HeaderText="%" />
                                <asp:TemplateField HeaderText="%">
                                    <ItemTemplate>
                                        <input type="text" id="textperc" runat="server" maxlength="5" class="textFieldStyle"
                                            onkeypress="javascript:return allowKeyAcceptsSingleDot('0123456789.');" value='<%# DataBinder.Eval(Container.DataItem, "Percentage") %>' />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <asp:CheckBox ID="chkwf" AutoPostBack="true" runat="server" Checked="true" OnCheckedChanged="getwf" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="ProcessFlow">
                                    <ItemTemplate>
                                        <asp:DropDownList Visible="false" ID="ddlWF" runat="server" CssClass="selectFieldStyle">
                                        </asp:DropDownList>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:BoundField DataField="Appr_Required" HeaderText="Appr_Required" />
                                <asp:BoundField DataField="WF_Id" HeaderText="WF_Id" />
                            </Columns>
                        </asp:GridView>
                    </div>
                    <div style="margin-top: 5px;">
                        <asp:Button ID="btnEdit" runat="server" Text="Update" CssClass="buttonStyle" Visible="False" />
                        <div id="loadingdiv" runat="server" style="display: none; position: absolute; width: 95%; text-align: center; top: 38%; left: 7px;">
                            <b>Please wait..</b>
                            <img src="../progress-bar.gif" runat="server" id="loading" alt="saving data" />
                        </div>
                    </div>
                </ContentTemplate>
            </asp:UpdatePanel>
        </div>
        <%--Modified by Fauzan, 7 Nov 2018. Remove 3 Logo--%>
        <%--<div style="text-align: right; width: 99%; vertical-align: bottom;">
            <img src="~/images/three-logo.png" alt="threelogo" runat="server" id="threelogoid" height="70" width="50" />
        </div>--%>
        &nbsp;&nbsp;
        <input type="hidden" id="hdnid" runat="server" />
        <input type="hidden" id="hdnScope" runat="server" />
        <input type="hidden" id="hdnSW_Id" runat="server" />
        <input type="hidden" id="hdnTotal" runat="server" />
    </form>
</body>
</html>
