<%@ Page Language="VB" AutoEventWireup="false" CodeFile="frmSiteDocStatus.aspx.vb" Inherits="frmSiteDocStatus" %>
<%@ Register Assembly="System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" Namespace="System.Web.UI" TagPrefix="asp" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title></title>
    <link href="../CSS/Styles.css" rel="stylesheet" type="text/css" /> 
    <script language="javascript" type="text/javascript">
        function checkIsEmpty()
        {
            var msg="";
            var e = document.getElementById("ddlWF"); 
            var strUser = e.options[e.selectedIndex].value;
            if (strUser == 0)
            {
                msg = msg + "Workflow should be select\n"
            }
            if (msg != "")
            {
                alert("Mandatory field information required \n\n" + msg);
                return false;
            }
            else
            {
                return accessConfirm();
            }          
        }
        function accessConfirm()
        {
            var r = confirm("Are you sure you want to save the details?");
            if (r == true)
            {
                return true;
            }
            else
            {return false;}
        }
        
//        function myPostBack()
//        {    
//          var o = window.event.srcElement;
//          if (o.tagName == "INPUT" && o.type == "checkbox")
//              {__doPostBack("","");
//              } 
//        }
    </script>
</head>
<body>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">        
            <ContentTemplate>        
                <table border="0" cellpadding="1" cellspacing="1" width="100%">
                    <tr class="pageTitle">
                        <td colspan="3"> Site Document Status</td>
                    </tr>
                    <tr style="height:5"><td colspan="3"></td></tr>
                    <tr>
                        <td class="lblTitle">Po No<font style="color:Red; font-size:16px"><sup> * </sup></font></td>
                        <td style="width:1%">:</td>
                        <td>
                            <asp:DropDownList ID="ddlPO1" runat="server" CssClass="selectFieldStyle" AutoPostBack="True"></asp:DropDownList></td>
                    </tr>
                    <tr>
                        <td class="lblTitle" style="height: 18px">Site<font style="color:Red; font-size:16px"><sup> * </sup></font></td>
                        <td style="width: 1px; height: 18px;">:</td>
                        <td style="height: 18px">
                            <asp:DropDownList ID="ddlSite" runat="server" AutoPostBack="true" CssClass="selectFieldStyle">
                            </asp:DropDownList>&nbsp;<asp:TextBox ID="txtSearch" runat="server" CssClass="textFieldStyle"  ></asp:TextBox>&nbsp;<asp:Button ID="btnSearch" runat="server" Text="Go" CssClass="goButtonStyle" OnClick="btnSearch_Click"/></td>
                    </tr>
                    <tr>
                        <td class="lblTitle" valign="top">Documents</td>
                        <td valign="top">:</td>
                        <td><asp:TreeView ID="TreeView1" runat="server" CssClass="tree" AutoGenerateDataBindings="false" NodeIndent="10" MaxDataBindDepth="4" ShowLines="True">
                            <ParentNodeStyle Font-Bold="True" ForeColor="Blue" />
                                    <RootNodeStyle Font-Bold="True" ForeColor="Blue" />            
                                    <SelectedNodeStyle BackColor="White" BorderColor="#888888" BorderStyle="None" BorderWidth="1px"
                                        Font-Underline="False" HorizontalPadding="1px" VerticalPadding="0px" />
                                    <NodeStyle CssClass="instructionalMessage" HorizontalPadding="1px"
                                        NodeSpacing="0px" VerticalPadding="0px" />
                            </asp:TreeView>
                            
                        </td>
                    </tr>
                    <tr><td class="SubPageTitle">Legend :</td></tr>
                    <tr><td colspan="3" class="lblText">Required & Uploaded : <img alt="" src="../Images/ok.jpg" runat="server" />&nbsp;<br />
                    Required & Not Uploaded : <img  alt="" id="Img1" src="../Images/notok.jpg" runat="server" />&nbsp;<br />
                    Not Required & Uploaded : <img alt="" id="Img2" src="../Images/Rok.jpg" runat="server" />&nbsp;
                    </td></tr>
                    <tr style="height:5"><td colspan="3"></td></tr>
                </table>
            </ContentTemplate>
        </asp:UpdatePanel>            
        <asp:HiddenField ID="hdndocid" runat="server" />
        &nbsp;&nbsp;&nbsp;&nbsp;
        
    </form>
</body>
</html>
