<%@ Page Language="VB" AutoEventWireup="false" CodeFile="frmGroupMenu.aspx.vb" Inherits="frmGroupMenu" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
     <table width="100%" cellpadding="0" cellspacing="1">
                <tr class="pageTitle"><td colspan="2">Access Rights</td></tr>
                <tr><td width=30></td><td>Select User Group : <asp:DropDownList id="ddlUserGroup" runat="server" cssclass="selectFieldStyle" AutoPostBack="True"></asp:DropDownList>&nbsp;&nbsp;<asp:Button ID="btnSave" Text="Save" runat="server" /></td></tr>
                <tr height=1 bgcolor=black><td colspan=2></td></tr>
                <tr><td width=30></td><td colspan=2>
                        <asp:TreeView ID="TreeView1" runat="server" CssClass="tree" ExpandDepth="2" MaxDataBindDepth="3" AutoGenerateDataBindings="False" OnClick="myPostBack();" NodeIndent="10" ShowLines="True" ShowCheckBoxes="All" Height="248px">
                            <ParentNodeStyle Font-Bold="True" ForeColor="Blue" />
                            <RootNodeStyle Font-Bold="True" ForeColor="Blue" />            
                            <SelectedNodeStyle BackColor="White" BorderColor="#888888" BorderStyle="None" BorderWidth="1px"
                                Font-Underline="False" HorizontalPadding="1px" VerticalPadding="0px" />
                            <NodeStyle CssClass="instructionalMessage" HorizontalPadding="1px"
                                NodeSpacing="0px" VerticalPadding="0px" />
                        </asp:TreeView>
                    </td></tr>            
                </table>          
    </div>
    </form>
</body>
</html>
