<%@ Page Language="VB" AutoEventWireup="false" CodeFile="MenuDisplay.aspx.vb" Inherits="MenuDisplay" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
    <link href="css/Styles.css" rel="stylesheet" type="text/css" />
    <script language="javascript" type="text/javascript">
    function myPostBack()
    {    
      var o = window.event.srcElement;
      if (o.tagName == "INPUT" && o.type == "checkbox")
          {
            __doPostBack("","");
          } 
    }
    </script>
</head>
<body style="background-color:#e3e3e3">
    <form id="form1" runat="server">
    <div>
    <asp:TreeView ID="TreeView1" runat="server" style="vertical-align: top; text-align: left" ExpandDepth="2" MaxDataBindDepth="3" AutoGenerateDataBindings="False" OnClick="myPostBack();" NodeIndent="5" ShowLines="True" ImageSet="BulletedList4" Height="248px" Width="135px" Font-Size="Smaller">
    <ParentNodeStyle Font-Bold="False" />
      <HoverNodeStyle Font-Underline="True" ForeColor="#5555DD" />
            <RootNodeStyle Font-Bold="True" ForeColor="Blue" />            
            <SelectedNodeStyle BackColor="White" BorderColor="#888888" BorderStyle="None" BorderWidth="1px"
                Font-Underline="False" HorizontalPadding="1px" VerticalPadding="0px" ForeColor="#5555DD" />
            <NodeStyle CssClass="instructionalMessage" HorizontalPadding="1px" NodeSpacing="0px" VerticalPadding="0px" />                
      </asp:TreeView>
    
    </div>
    </form>
</body>
</html>
